/* Generated By:JavaCC: Do not edit this line. ProtoBufParserConstants.java */
package com.satori.codegen.pbuf2jschema.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProtoBufParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MESSAGE = 5;
  /** RegularExpression Id. */
  int REQUIRED = 6;
  /** RegularExpression Id. */
  int OPTIONAL = 7;
  /** RegularExpression Id. */
  int REPEATED = 8;
  /** RegularExpression Id. */
  int SYNTAX = 9;
  /** RegularExpression Id. */
  int OPTION = 10;
  /** RegularExpression Id. */
  int PACKAGE = 11;
  /** RegularExpression Id. */
  int EXTENSIONS = 12;
  /** RegularExpression Id. */
  int ENUM = 13;
  /** RegularExpression Id. */
  int DEF = 14;
  /** RegularExpression Id. */
  int TO = 15;
  /** RegularExpression Id. */
  int TYPE_INT = 16;
  /** RegularExpression Id. */
  int TYPE_STRING = 17;
  /** RegularExpression Id. */
  int TYPE_BIN = 18;
  /** RegularExpression Id. */
  int TYPE_BOOL = 19;
  /** RegularExpression Id. */
  int TYPE_LONG = 20;
  /** RegularExpression Id. */
  int TYPE_DOUBLE = 21;
  /** RegularExpression Id. */
  int TYPE_FLOAT = 22;
  /** RegularExpression Id. */
  int ALPHA = 23;
  /** RegularExpression Id. */
  int DIGIT = 24;
  /** RegularExpression Id. */
  int NUMBER = 25;
  /** RegularExpression Id. */
  int ID = 26;
  /** RegularExpression Id. */
  int LINE_COMMENT = 28;
  /** RegularExpression Id. */
  int QUOTE = 30;
  /** RegularExpression Id. */
  int ENDQUOTE = 31;
  /** RegularExpression Id. */
  int STRING = 32;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_LINE_COMMENT = 1;
  /** Lexical state. */
  int STRING_STATE = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"message\"",
    "\"required\"",
    "\"optional\"",
    "\"repeated\"",
    "\"syntax\"",
    "\"option\"",
    "\"package\"",
    "\"extensions\"",
    "\"enum\"",
    "\"default\"",
    "\"to\"",
    "<TYPE_INT>",
    "\"string\"",
    "\"bytes\"",
    "\"bool\"",
    "<TYPE_LONG>",
    "<TYPE_DOUBLE>",
    "<TYPE_FLOAT>",
    "<ALPHA>",
    "<DIGIT>",
    "<NUMBER>",
    "<ID>",
    "\"//\"",
    "<LINE_COMMENT>",
    "<token of kind 29>",
    "\"\\\"\"",
    "<ENDQUOTE>",
    "<STRING>",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\";\"",
    "\"[\"",
    "\"]\"",
  };

}
